#
# Main authors:
#    Vincent Barichard <Vincent.Barichard@univ-angers.fr>
#
# Copyright:
#    Vincent Barichard, 2013
#
# Last modified:
#    $Date$ by $Author$
#    $Revision$
#
# This file is part of Quacode:
#    http://quacode.barichard.com
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# CMake package to find Gecode libraries and set usefull variables

SET(GECODE_SEARCH_PATH ${GECODE_BIN} /usr/lib /usr/local/lib)

FIND_LIBRARY(GECODE_KERNEL_LIBRARIES gecodekernel ${GECODE_SEARCH_PATH}) 

IF(GECODE_KERNEL_LIBRARIES)
  SET(GECODE_FOUND TRUE)
  GET_FILENAME_COMPONENT(LPATH ${GECODE_KERNEL_LIBRARIES} PATH)
  SET(GECODE_KERNEL_LIBRARIES "-L${LPATH} -lgecodekernel")
  SET(GECODE_LIBRARIES ${GECODE_KERNEL_LIBRARIES})

  FIND_LIBRARY(GECODE_SUPPORT_LIBRARIES gecodesupport ${GECODE_SEARCH_PATH}) 
  IF(GECODE_SUPPORT_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_SUPPORT_LIBRARIES} PATH)
    SET(GECODE_SUPPORT_LIBRARIES "-L${LPATH} -lgecodesupport")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_SUPPORT_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_SUPPORT_LIBRARIES)

  FIND_LIBRARY(GECODE_INT_LIBRARIES gecodeint ${GECODE_SEARCH_PATH}) 
  IF(GECODE_INT_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_INT_LIBRARIES} PATH)
    SET(GECODE_INT_LIBRARIES "-L${LPATH} -lgecodeint")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_INT_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_INT_LIBRARIES)

  FIND_LIBRARY(GECODE_FLOAT_LIBRARIES gecodefloat ${GECODE_SEARCH_PATH}) 
  IF(GECODE_FLOAT_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_FLOAT_LIBRARIES} PATH)
    SET(GECODE_FLOAT_LIBRARIES "-L${LPATH} -lgecodefloat")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_FLOAT_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_FLOAT_LIBRARIES)

  FIND_LIBRARY(GECODE_SET_LIBRARIES gecodeset ${GECODE_SEARCH_PATH}) 
  IF(GECODE_SET_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_SET_LIBRARIES} PATH)
    SET(GECODE_SET_LIBRARIES "-L${LPATH} -lgecodeset")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_SET_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_SET_LIBRARIES)

  FIND_LIBRARY(GECODE_SEARCH_LIBRARIES gecodesearch ${GECODE_SEARCH_PATH}) 
  IF(GECODE_SEARCH_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_SEARCH_LIBRARIES} PATH)
    SET(GECODE_SEARCH_LIBRARIES "-L${LPATH} -lgecodesearch")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_SEARCH_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_SEARCH_LIBRARIES)

  FIND_LIBRARY(GECODE_MINIMODEL_LIBRARIES gecodeminimodel ${GECODE_SEARCH_PATH}) 
  IF(GECODE_MINIMODEL_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_MINIMODEL_LIBRARIES} PATH)
    SET(GECODE_MINIMODEL_LIBRARIES "-L${LPATH} -lgecodeminimodel")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_MINIMODEL_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_MINIMODEL_LIBRARIES)

  #  FIND_LIBRARY(GECODE_FLATZINC_LIBRARIES gecodeflatzinc ${GECODE_SEARCH_PATH}) 
  #  IF(GECODE_FLATZINC_LIBRARIES)
  #    GET_FILENAME_COMPONENT(LPATH ${GECODE_FLATZINC_LIBRARIES} PATH)
  #    SET(GECODE_FLATZINC_LIBRARIES "-L${LPATH} -lgecodeflatzinc")
  #    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
  #    SET(GECODE_LIBRARIES "${GECODE_FLATZINC_LIBRARIES} ${GECODE_LIBRARIES}")
  #  ENDIF(GECODE_FLATZINC_LIBRARIES)

  FIND_LIBRARY(GECODE_DRIVER_LIBRARIES gecodedriver ${GECODE_SEARCH_PATH}) 
  IF(GECODE_DRIVER_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_DRIVER_LIBRARIES} PATH)
    SET(GECODE_DRIVER_LIBRARIES "-L${LPATH} -lgecodedriver")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_DRIVER_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_DRIVER_LIBRARIES)

  FIND_LIBRARY(GECODE_GIST_LIBRARIES gecodegist ${GECODE_SEARCH_PATH}) 
  IF(GECODE_GIST_LIBRARIES)
    GET_FILENAME_COMPONENT(LPATH ${GECODE_GIST_LIBRARIES} PATH)
    SET(GECODE_GIST_LIBRARIES "-L${LPATH} -lgecodegist")
    STRING(REPLACE "-L${LPATH} " "" GECODE_LIBRARIES ${GECODE_LIBRARIES})
    SET(GECODE_LIBRARIES "${GECODE_GIST_LIBRARIES} ${GECODE_LIBRARIES}")
  ENDIF(GECODE_GIST_LIBRARIES)

ENDIF(GECODE_KERNEL_LIBRARIES)

IF(GECODE_FOUND)
  MESSAGE(STATUS "Found GECODE: ${GECODE_LIBRARIES}")
ELSE (GECODE_FOUND)
  MESSAGE(STATUS "Could not find GECODE")
ENDIF(GECODE_FOUND)
